### ISSUE TITLE
Force Singed-off line by Github

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/platform-launcher#114]
This is not something humans should be checking.

**Comment by wagmarcel** [comment]
I could not find the setting for the whole project. But it can be forced for every develop/master branch individually, when you go to settings => branches => branch protection rules and then selecting "Require signed commits"
I did it for the main OISP projects, please do it for your repos.

**Comment by arkocal** [comment]
OK. Closing the issue, please reopen if you see a repo that does not require signed commits.

**Comment by arkocal** [comment]
Important note: We should do it on master as well so that we do not have any surprises when merging.
