### ISSUE TITLE
Database User Privileges

### ISSUE THREAD

**Issue by maxdos64** [Open-IoT-Service-Platform/platform-launcher#137]
There is only one user in the database "postgres" which
has complete admin privileges.
Should a sql query breach occur the whole database and its managment is
immediatly compromised.
There should be seperate users for the seperate databases and one might 
even think about restricting those users right to DROP tables etc...

Explicitly mind the shell execution priviliges supported by Postgresql > 9.3
https://www.postgresql.org/about/news/1935/

**Comment by oguzcankirmemis** [comment]
This issue is resolved after [e385c51](https://github.com/Open-IoT-Service-Platform/oisp-frontend/commit/e385c517e8a50d1d4e3d0464c7c9f67b9331a4a1),  closing...
