### ISSUE TITLE
build backend failed

### ISSUE THREAD

**Issue by chuan9** [Open-IoT-Service-Platform/platform-launcher#17]
make build
build backend failed. log is:
/app/src/main/java/com/intel/databackend/api/kafka/KafkaSenderService.java:68: error: incompatible types: ZkClient cannot be converted to ZkUtils
                if (!AdminUtils.topicExists(zkClient, topic)) {
                                            ^
/app/src/main/java/com/intel/databackend/api/kafka/KafkaSenderService.java:70: error: method createTopic in class AdminUtils cannot be applied to given types;
                    AdminUtils.createTopic(zkClient, topic, partitions, replicationFactor, new Properties());
                              ^
  required: ZkUtils,String,int,int,Properties,RackAwareMode
  found: ZkClient,String,Integer,Integer,Properties
  reason: actual and formal argument lists differ in length
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 10.891 secs
Makefile:29: recipe for target 'build' failed
make: *** [build] Error 1
ERROR: Service 'backend' failed to build: The command '/bin/sh -c make build' returned a non-zero code: 2
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images

**Comment by wagmarcel** [comment]
Hi, 
thanks for reporting this.
This will be fixed by @jelyoussefi  by reverting last commit on backend.

**Comment by wagmarcel** [comment]
fixed
