### ISSUE TITLE
E2E Test preparation for client applications

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#171]
The test is today executed with make test. Then the whole test suite is executed which takes time.
There are client applications like oisp-iot-agent which need to be tested with most recent OISP service. These applications need to know when the service is ready and get access to a default account with either user-token or username/password.
The new test preparation feature should work as follows:
- It is started with `make test-prep-only`
- It makes sure the service is ready and provides a file `oisp-prep-only.conf` which contains account details

**Comment by arkocal** [comment]
5e0076bced308973a36936950dd9acdf0ee8a1bc fixes this.
