### ISSUE TITLE
Merging k8s and refactoring

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/platform-launcher#184]
As you know, we are moving away from docker-compose as a testing platform, which is obviously bringing some breaking changes.  Since `kubernetes` is going to be the only supported way of running oisp, the oisp-k8s repo should be merged into this one as @wagmarcel suggested. This also means that many parts of this project are going be become unnecessary, and can be remove for the sake of simplicity and consistency. Below are my suggestions for the reorganisation, file by file:

* `LICENSE` Both projects have the same license, so they can be merged without any problems. The file obviously remains.
* `README.md` is already outdated, and is rarely updated. We should rewrite this file in a very minimal form, with couple of good examples on how to use OISP and link the documentation for detailed descriptions.
* `data` directory is only used by hbase during build, which is problematic anyway. keys should be implemented using kubernetes secrets, and this directory should be removed.
* `docker.sh` is also only going to be used for build-time, and can easily be integrated into the `Makefile` and removed.
* `documentation` is incomplete and outdated (it only contains an outdated dump of frontend API documentation). It should be created from scratch and populated using the documentation scattered around wikis and READMEs. [Read the docs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) integration would be nice. Using `sphinx` over `markdown` we could also integrate the raml & pydoc documentations and cross reference other documentations. Plugins for other documentation tools such as oxygen also exist. Creating a complete documentation would be too time consuming, but I think we should at least bring the basics together.
* `oisp-*` subrepos should stay the way they are.
* `setup-environment.sh` is only relevant for runtime and should be removed.
* `tests` are also going to need heavy refactoring/simplification. Most of the boilerplate introduced by supporting docker-compose and kubernetes at the same time has accumulated in tests.As of now everything works on kubernetes manually and with circleci, so this should be doable, and removal of docker-compose stuff has no high priority.
* `Makefile` most of the docker-compose and runtime relevant commands should be taken out, it can also be merged with the makefile from the oisp-k8s repo.
* `config-backup` only contains backups of runtime configuration, and should be removed.
* `docker` directory created by #183 contains the images that do not have their own subrepos. In the long run they should be replaced by operators, as they are not components that we are maintaining ourselves. (postgres can be removed immediately since it is not used in the k8s implementation)
* `docker-compose.yaml` contains many runtime parameters that should be removed. This file will only be used for builds, therefor the standard components that we are not building should be removed as well.
* `platform-setup` should also be removed, since the requirements have changed. It should be replaced by the platform-setup in the oisp-k8s repo.
* From oisp-k8s repo, utils such as scripts and makefile should land in the root directory. The rest should stay as a valid helm repo.

## How to merge
1. Do the non-breaking refactoring, such as #183 
2. merge the oisp-k8s repo as a directory.
3. Change the automated tests those in k8s repository.
4. Gradually perform rest of the refactoring and simplification.

After 3. is complete, any PRs that fail the tests that are then running on k8s should be denied.

## Development on k8s
Currently, a new image has to be built every time changes are made to repository for testing. Using the script `util/build-and-import-images.sh` in the oisp-k8s repository, the process of pushing and repulling the images can be skipped. I believe this is acceptable, but there is a lot of room for improvement, and I am open for suggestions.

**Comment by arkocal** [comment]
#185 would perform the second step of the migration without losing the history of the repository.

**Comment by oguzcankirmemis** [comment]
@arkocal not sure if it was my fault or it was an unsupported behavior:

If you try to open grafana via dashboard, then a page with url http://dashboard/ui/grafana/... (with default port 80) will be requested. Then the reverse proxy server(formerly nginx) would change the port to where grafana proxy server listens. So far this setup also works in k8s (thanks to you :)). In development environment though, where I use kubernetes without ingresses, this does not work and therefore I have some struggles with testing grafana itself. A little scenario:

- Running frontend locally after some changes in grafana proxy server
- Starting e2e-tests
- Grafana tests fail because they make the request to port 80, assuming it would be handled by the reverse proxy server

I can fix this by changing the port manually at e2e test, so this is not an urgent problem, but it would be nice to have if a solution for it exists.

**Comment by arkocal** [comment]
This is completed, closing.
