### ISSUE TITLE
Helper script for getting environment variables

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/platform-launcher#197]
After getting tired of exporting new environment variables for every new deployment (for local development purposes), I have decided to write a helper script, here is how it looks like:

```bash
NAMESPACE="oisp"
CONTAINER_NAME=$1
BLACKLISTED_VARS="HOME\|PWD\|OLDPWD\|TERM\|PATH\|HOSTNAME"
POD_NAME=$(kubectl -n ${NAMESPACE} get pods | grep ${CONTAINER_NAME} | cut -f 1 -d " ")
kubectl -n ${NAMESPACE} exec ${POD_NAME} -- /bin/bash -c "export -p" | grep -v ${BLACKLISTED_VARS}
```

Using this script I can easily set the environment variables with one command:
`source <(get_oisp_container_config.sh dashboard)`

Would this be useful? If so, I could expand it a bit more and we can put this into utils.

**Comment by arkocal** [comment]
This looks quite useful. Do you think it can be used generically (the only point I think that could be risky is whether the blacklist is enough for all). 

It would also be good to document this to indicate that the values are drawn from running containers, and not extracted from the config.

**Comment by oguzcankirmemis** [comment]
Generally, it should work for any container (tested with websocket too), I can also implement the functionality of expanding the blacklist. The ones I am blacklisting are the core ones, so the existing environment variables does not get deleted by the new ones.
