### ISSUE TITLE
Unit tests require updating following Node.js repository refactoring

### ISSUE THREAD

**Issue by srware** [Open-IoT-Service-Platform/platform-launcher#21]
Unit tests need updating after the Node.js packages were split into separate repositories.

IoT Agent: https://github.com/Open-IoT-Service-Platform/oisp-iot-agent
CLI: https://github.com/Open-IoT-Service-Platform/oisp-cli
SDK: https://github.com/Open-IoT-Service-Platform/oisp-sdk-js

The Agent and CLI now pull the SDK from NPM.

**Comment by wagmarcel** [comment]
updated in develop. Removed submodule and added npm package.
