### ISSUE TITLE
K8s: Using different ingress controllers

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/platform-launcher#211]
I was investigating about why the routing of grafana was failing in deployment but not in the test environment. I found out that these clusters use different ingress controllers which causes the problem.

- When I deploy the cluster locally, Traefik is used as an ingress controller.
- When it is deployed in production mode (see circleci nightly deployment), another controller is used (which I could not figure out, but it seemed like an nginx based controller).

The problem is on production, sub paths are not supported or not configured right, but then again, fixing it for production means breaking it in local development.

Can we make sure that the same controller is used in both environments so that we have only one configuration file? Kubernetes [documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource) mentions that all controllers should support the same syntax, but still differentiating in minor details like this.

**Comment by wagmarcel** [comment]
@oguzcankirmemis: On latest.streammyiot.com, HAProxy is the default ingress controller provided by the CSP. Can you please describe in more detail what is not working? Maybe we can find the configuration working on HAProxy as well.

**Comment by oguzcankirmemis** [comment]
@wagmarcel Thanks for the information. I can dive into more details with this. Basically the problem is when we have two different paths on the same host - in our example the paths are '/' and '/ui/grafana' and host is 'latest.streammyiot.com' that we want to run seperately, the Traefik ingress controller can work with our config, but probably HAProxy wants a different annotation. Here is the current config [file](https://github.com/Open-IoT-Service-Platform/platform-launcher/blob/develop/kubernetes/templates/ingress.yaml). I will try to make a config that works on both controllers, if this is not possible then we could discuss what we are going to do.

**Comment by oguzcankirmemis** [comment]
@wagmarcel @arkocal It seems HAProxy is using a first beginning match policy with an ascending order of the length of the paths . This means, with our configuration we observe this behavior:

- path '/' redirects to frontend
- path '/ui/grafana' redirects to grafana proxy
- path '/ui/grafana' has higher length, therefore path '/' has a higher priority.
- request to '/ui/grafana/*' arrives, it gets matched to '/' because of its higher priority, and request is redirected to frontend

There were some solutions using target_rewrite annotation, but I could not bring them to work with HAProxy. I've also tried many regular expressions, just to see if I could change priorization and I've failed.

I can suggest two solutions:

- Run grafana proxy server under frontend, this means grafana proxy will also serve under the frontend using the same port with its path (e.g '/ui/grafana' or something else)
- Run grafana proxy server under a different hostname like 'grafana.streammyiot.com'. But this seems a bit problematic, because dashboard must then make requests to this host and the hostname changes in development/deployment.

**Comment by wagmarcel** [comment]
I just found out that we can deploy our own ingress as long as CSP provides load-balancer IP. I tested successfully nginx-ingress on a test-cluster. So in future we should not setup HAproxy support for the cluster. Much rather, I will provide a recipe how to deploy nginx ingress-controller.
