### ISSUE TITLE
HBase Master/Region does not restart on fail (OpenTSDB can't reach to them)

### ISSUE THREAD

**Issue by oguzcankirmemis** [Open-IoT-Service-Platform/platform-launcher#253]
After running the deployment for a long time (in our case staging.streammyiot.com). Somehow in the way OpenTSDB started to fail due to a fail in Hbase/Zookeeper. Then Hbase/Zookeeper restarted itself but due to some reason OpenTSDB did not crash. Instead it raised a PleaseThrottleException for every data search request. After restarting OpenTSDB manually, the problem was gone. I think OpenTSDB should crash itself if such an error occurs and restart again. Otherwise we will have to do it manually.

**Comment by arkocal** [comment]
@oguzcankirmemis is there any other way you know for checking this apart from reading the logs?

**Comment by oguzcankirmemis** [comment]
I've investigated it further. It turns out OpenTSDB raises this exception if it can't reach to HBase region. To solve it, I've had to restart HBase master/region pods. There was no need to restart OpenTSDB. The problem is there isn't any error log in the region/master pods, so I had no way to find out what the problem actually was. Changing the Issue title as the current one is deceiving.

**Comment by arkocal** [comment]
Closing this since we do not have hbase anymore.
