### ISSUE TITLE
Make remove always removes all containers

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/platform-launcher#42]
Here is a modified version of the `Makefile` for testing without actually deleting the containers:
```make
ifeq (remove,$(firstword $(MAKECMDGOALS)))
 	CMD_ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
 	$(eval $(CMD_ARGS):;@:)
endif

remove:
	@$(call msg,"Removing $(CMD_ARGS) ...");
	echo $(MAKECMDGOALS)
ifeq ($(CMD_ARGS),)
	echo "Removing single container"
#	@./docker.sh stop $(docker ps -a -q);
#	@./docker.sh rm -f $(docker ps -a -q);
#	@/bin/bash -c "docker images -q | xargs -n 1 -I {} docker rmi -f {}"

else
	echo "Removing all containers"
#	@$(foreach container,$(CMD_ARGS), \
#		./docker.sh stop $(container); \
#		./docker.sh rm -f -v $(container); \
#		docker images | grep  "^.*$(container)" | awk '{print $$3}' | xargs -n 1 -I {} docker rmi -f {}; \
#	)
 endif
```

When I run `make remove anycontainername` it still prints `Removing all containers`. Can you check whether you can reproduce this issue, or is this system dependent?

In all cases, there should also be a warning question which defaults to No, as deleting containers causes a huge loss of time.

**Comment by jelyoussefi** [comment]
It works fine on Ubuntu. I'll take a look

**Comment by arkocal** [comment]
I believe it is not OS dependent but shell, I am using zsh.
But I actually thought it should not make a difference as shell is specified in the Makefile.

**Comment by arkocal** [comment]
e9464eab77540affa2f1a6e6ba95e033828568e0 resolves this.
