### ISSUE TITLE
Database misconfiguration on latest

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#460]
Mismatch between oisp-config and database.
All secrets seem to be wrong.
frontend should use the oisp-user but uses now admin
Changes happened with db username during the zalando introduction
Task: Recover the oisp-user in frontend and mqtt-gateway (but wait for test results from 2.0.3 to 2.1.0 transition)

related to #459

**Comment by oguzcankirmemis** [comment]
There were no problems in transitioning from 2.0.3 to 2.1.0. oisp_user has also been recovered and everything is back to normal, closing.
