### ISSUE TITLE
MQTT feedback channel

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#515]
- [x] MQTT will be used as general feedback channel
- [x] Websocket server will be removed
- [x] #579
- [x] #576
- [x] https://github.com/Open-IoT-Service-Platform/oisp-iot-agent/issues/36
- [x] Gateway ID not properly handled
- [x] #577
- [x] Update JS SDK
- [x] #599

**Comment by oguzcankirmemis** [comment]
This is not yet completely finished, reopening...

**Comment by oguzcankirmemis** [comment]
First iteration of the feedback channel is ready, the new feedback format which is compliant with Sparkplug B looks like this: 
```javascript
TOPIC_NAME = "server/{accountId}/DCMD/{gatewayId}/{deviceId}"
{
    timestamp: 1639121171343,
    metrics: [ {
        timestamp: 1639121171343,
        name: "LED",
        dataType: "Boolean",
        value: true,
        cid: "a4c59747-56d1-47eb-b597-e848d6526642",
        command: "LED.v.1.0"
    } ]
}
```
The 'server' prefix in the topic name can be adjusted by setting the 'topicsPrefix' variable in the MQTT environment config.

First iteration also includes additional E2E tests. Frontend now forwards feedback to Kafka but also to Redis, for backwards compatibility.

Additional things to do:

- Remove Redis forwarding after websocket is removed
- Add account id based partitioner to kafka forwarding in frontend.

**Comment by wagmarcel** [comment]
Status: Waiting for iot-Agent integration

**Comment by wagmarcel** [comment]
Status: Actuations feedback working.
E2E-test not yet working

**Comment by oguzcankirmemis** [comment]
All subtasks are closed, closing issue...
