### ISSUE TITLE
Update api spec

### ISSUE THREAD

**Issue by chuan9** [Open-IoT-Service-Platform/platform-launcher#55]
https://streammyiot.com/ui/public/api.html#v1_api_users->/v1/api/users
>>The following access-roles are authorized for this path: anon
need to be modified to:
"The following access-roles are authorized for this path: admin, anon"

**Comment by arkocal** [comment]
The documentation states `Closed or single tenant systems could protect by requesting an authenticated access role like admin.`, I think this is enough, closing.
