### ISSUE TITLE
Fix log4j for oisp services

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#563]

**Comment by MericFeyz** [comment]
The traces of log4j were present in 3 subfolders in this repository. The first one is under ```metrics-aggregator/src/main/resources/log4j.xml```, which is obsolete and dead code that does not run. The second one is under ```simple-flink-sql-gateway/udf/Epoch2SQL/pom.xml```, which uses the version 1.2.17 of Log4j. The 1.* versions of Log4J does not feature the JNDI, which enables the Log4Shell vulnerability, therefore Log4J 1.2.17 is safe from the vulnerability. The third one is under ```simple-flink-sql-gateway/udf/GetJsonField/pom.xml``` and uses 2.12.1 version of the Log4J, which is affected by the Log4Shell. The linked PR will bump the version from 2.12.1 to the most up to date version 2.17.1, in which the vulnerabilities have been patched. Rest of the code is not vulnerable to the Log4Shell.
