### ISSUE TITLE
Fix log4j for KairosDB

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#566]

**Comment by MericFeyz** [comment]
The image we are basing this image on is ```openjdk:8-jdk``` which is safe from the log4shell vulnerability per Dockerhub's [security scans](https://hub.docker.com/layers/openjdk/library/openjdk/8-jdk/images/sha256-9413213335131c4e06b21a8e379bd9b6a20afcd6b762540463d5f7c72942dcdd?context=explore). In addition Cassandra ,which KairosDB is based on, is also safe from log4shell vulnerability per [discussions on the forums](https://lists.apache.org/thread/2rngylxw8bjos6xbo1krp29m9wn2hhdr).

A scan with [grype](https://github.com/anchore/grype) showed no log4shell vulnerability either.
