### ISSUE TITLE
Fix log4j for debugger

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#567]

**Comment by MericFeyz** [comment]
The base image ```ubuntu:18.04``` is safe from log4shell per Dockerhub [security scans](https://hub.docker.com/layers/ubuntu/library/ubuntu/18.04/images/sha256-66504687c64ca60db9f451c76c8306af50b276c28c614f18c4ae34007fa244ad?context=explore).

A scan of the entire image with [grype](https://github.com/anchore/grype) showed no vulnerability to log4shell either.
