### ISSUE TITLE
Sparkplug B integration in MQTT Gateway and as standalone component for agent

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#584]
- [x] Agent
- [x] MQTT Gateway

**Comment by wagmarcel** [comment]
Decision: Change the type field semantic in the agent devices.json file to contain data type rather than catalogue item.

**Comment by yshashix** [comment]
Pull request created for sending data from device to mqtt-gw->kafka bridge using sparkplugB standard data format
