### ISSUE TITLE
Adding gatewayID in data/device.json file for device after activate command

### ISSUE THREAD

**Issue by yshashix** [Open-IoT-Service-Platform/platform-launcher#609]
Currently, gateway Id in data/device.json after activating the device is false by default, though the activation response contains the gatewayId(default is deviceId):
 In data/device.json:
 
    "gateway_id": false,
 
 - It should also update gateway_id,

**Comment by wagmarcel** [comment]
is currently part of PR - part of retirement of activation endpoint
