### ISSUE TITLE
deploy-operators.sh must be called from the util folder

### ISSUE THREAD

**Issue by MericFeyz** [Open-IoT-Service-Platform/platform-launcher#643]
Else it cannot find the ```kubernetes/cert-manager/clusterissuer-self-cert.yaml``` file. ```make restart-cluster``` calls it from the util directory but ```make upgrade-oisp``` does not.

**Comment by oguzcankirmemis** [comment]
@MericFeyz I guess this can be closed, right?

**Comment by MericFeyz** [comment]
Yes it will be fixed in a later date.
