### ISSUE TITLE
Scorpio aio

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#653]
https://github.com/IndustryFusion/DigitalTwin/issues/177

**Comment by MericFeyz** [comment]
After internal discussions it has been decided that it would be best to focus on the original and up-to-date Scorpio Broker repository, at least for the purposes of creating a test build involving AIO (All-in-one) Runner.

**Comment by wagmarcel** [comment]
We will use directly the Quarkus version of Scorpio and also abandon Spring boot. 
1st step: Make Default Quarkus image (java-3-0-0) run and use the database (non Kafka version)
2nd step: Use upstream helm chart description (use helmfile to configure or create minimal changes rebased on upstream)
3rd step: Integrate OIDC (Keycloak and roles as defined in the old project)


Preferred way is configuration of github containers (for postgres it likely works, for Keycloak that has to be analyzed)

**Comment by wagmarcel** [comment]
Use In_memory profile to avoid Kafka
java-3.0.1 should be used

**Comment by wagmarcel** [comment]
Expected Next week version with Postgres (no Kafka)

**Comment by wagmarcel** [comment]
Problems with ssl in Scorpio postgres connection. Vert.x not supporting ssl, will be fixed one day. Until then we configure postgres to accept unencrypted connections

**Comment by wagmarcel** [comment]
Quarkus version now working with Keycloak - tests not yet passing but very close to it

**Comment by yshashix** [comment]
- e2e test on progress , after it's success PR will be created

**Comment by wagmarcel** [comment]
Issue on Java version. Ubuntu 20.04 installs Java 11, but Scorpio needs Java 17(is a lower version possible?)
