### ISSUE TITLE
Simplify OISP accountId & Keycloak management

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#673]

**Comment by wagmarcel** [comment]
- [ ] Accounts are configurable in Keycloak
- [ ] Super-admin with rights to create tenants
- [ ] Device field must not use sub field
- [ ] Realm should be in token as single source of info for sparkplugb; use it to replace accoundID of spB endpoint

**Comment by yshashix** [comment]
- Authorization changes needed at oisp-mqtt gw : see acl and auth, they uses gatewayid as eonID for spB node message authorization creation and allowing access 
- adapt changes of cid and datatype validation at mqtt-gw
