### ISSUE TITLE
Minio-operator problem

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#701]
Cf https://github.com/IndustryFusion/DigitalTwin/issues/248

Create a reproducible test-case for the error

**Comment by yshashix** [comment]
Was problem due to removal of credsecret field in tenant spec in newer version of minio operator.
Stick to specific updated version

**Comment by wagmarcel** [comment]
Can we use an explicit target version of minio using krew? Can we update to a specific version with kubectl minio?

**Comment by yshashix** [comment]
Using krew we can update minio version but it does not allow to specify which exact version upgrade should it take.
The update command is < kubectl krew upgrade minio >
So possible method to stick to a version is by using a binary downloaded

**Comment by yshashix** [comment]
PR created in DT:  Ubuntu 20.04 & 22.04 support + Kafka upgrade 3.3 + minio fix to specific version
