### ISSUE TITLE
E2E test of Sparkplug-B data

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#705]
- NGSI-LD over MQTT
- Sparkplug-B without sequence numbers
- with sequence numbers
- use IoT-agent

**Comment by yshashix** [comment]
Needs to update bats version from 1.2.1, update to current 1.9.0 for setup_file functionality of bat. (Run once setup for every bats test file)

**Comment by yshashix** [comment]
Updated bats and created PR in DT.
Parsing Response from frontend

- Added OISP-IOT Agent  tag v2.4 as well for e2e test

**Comment by yshashix** [comment]
PR Created #724
