### ISSUE TITLE
OISP CI pipeline failing much earlier than it should fail

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#716]
failing not deterministically - when it tries to install  velero

**Comment by yshashix** [comment]
I got this issue in my local installation as well. I find that helm installation gave error like below
```
" STDERR:Error: no repository definition for https://vmware-tanzu.github.io/helm-charts. Please add the missing repos via 'helm repo add'
"
```
- URL with "." in end is not reacheable

- I solved it by removing Chart.lock of Velero chart and re-installation
