### ISSUE TITLE
Scorpio performance test  for entity and batchEntity

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/platform-launcher#726]
- Write requests
- Read requests

**Comment by MericFeyz** [comment]
20000 individual concurrent writes without failure in 0:01:01.794437
Resource usage of scorpio and zalando pods should be investigated during stress tests, as well as the difference between creating entities in batches and individually.
Retrieving entities is only possible with a maximum of 1000 at a time. Getting entities by type ( Request: ```GET ngsild.local/ngsi-ld/v1/entities?type=urn:mytypes:room&limit=1000```) becomes costlier when the database gets considerably bigger. Example: 20000 entities of type ```urn:mytypes:room``` in ngb database. Running the previously mentioned command took 430ms. With limit=5 it becomes ~280ms. When you retrieve a specific entity with id, then it takes ~15-20ms no matter how many entities there are in database.
